#!/bin/bash

usage() {
    echo "usage: make_examples_tarball tarfile" >&2
    exit 2
}

[ $# -eq 1 ] || usage

tar --exclude='*/.*.swp' --exclude='*/.pyhist' --exclude='*/compiled_krb*' \
    --exclude='*.py[co]' -czf "$1" examples
