#!/bin/bash

# testpyke [ errorfiles_file ]
#
# no arguments.
#
# run in pyke source directory to test all doctests.
# 
# exit status > 0 if errors found.

ERRORFILES="/tmp/testpyke.$$"

> $ERRORFILES
NUM_ERRORS=0

for f in `find . -name '*.py' ! -name '*_[bf]c.py'`
do
    echo Testing "$f"
    if ! python2.5 "$f"
    then
        echo "$f" >> $ERRORFILES
        NUM_ERRORS=$(($NUM_ERRORS + 1))
    fi
done

if [ $NUM_ERRORS -eq 0 ]
then
    echo Testing compiler.krb
    cd krb_compiler
    rm -rf compiled_krb
    if python2.5 -c "from pyke import krb_compiler; krb_compiler.compile('.', 'compiled_krb', ('compiler.krb',))"
    then
        if diff -q compiler_bc.py compiled_krb/compiler_bc.py
        then
            rm -rf compiled_krb
        else
            echo "krb_compiler/compiler.krb not compiled!" >> $ERRORFILES
            NUM_ERRORS=$(($NUM_ERRORS + 1))
        fi
    else
        echo "krb_compiler/compiler.krb" >> $ERRORFILES
        NUM_ERRORS=$(($NUM_ERRORS + 1))
    fi
    cd ..
fi

if [ $NUM_ERRORS -eq 0 ]
then
    echo "No Errors!"
    rm -f $ERRORFILES
else
    echo "********** ERRORS ************* $NUM_ERRORS files had errors:"
    cat $ERRORFILES
    if [ $# -gt 0 ]
    then
        sed 's,^\.,pyke,' $ERRORFILES >> "$1"
    fi
    rm -f $ERRORFILES
    exit $NUM_ERRORS
fi
