#!/bin/bash

# testpyke
#
# no arguments.
#
# run in pyke source directory to test all doctests.
# 
# exit status > 0 if errors found.

ERRORFILES="/tmp/testdocs.$$"

> $ERRORFILES
NUM_ERRORS=0

for f in `find . -name '*.py'`
do
    echo Testing "$f"
    if ! python2.5 "$f"
    then
        echo "$f" >> $ERRORFILES
        NUM_ERRORS=$(($NUM_ERRORS + 1))
    fi
done

if [ $NUM_ERRORS -eq 0 ]
then
    echo "No Errors!"
    rm -f $ERRORFILES
else
    echo "********** ERRORS ************* $NUM_ERRORS files had errors:"
    cat $ERRORFILES
    rm -f $ERRORFILES
    exit $NUM_ERRORS
fi
