#!/bin/bash

# testdocs [-p python_command] [ errorfiles_file ]
#
# no arguments.
#
# run in doc directory to test all .txt files.
# 
# exit status > 0 if errors found.

ERRORFILES="/tmp/testdocs.$$"
export PYTHONPATH="examples:$PYTHONPATH"

PYTHON="python2.5 -Wd"

if [ $# -ge 2 -a "x$1" = x-p ]
then
    PYTHON="$2"
    shift 2
fi

> $ERRORFILES
NUM_ERRORS=0

for f in `find source -name '*.txt'`
do
    #echo Testing "$f"
    if ! $PYTHON ../doctest_file.py "$f"
    then
        echo "$f" >> $ERRORFILES
        NUM_ERRORS=$(($NUM_ERRORS + 1))
    fi
done

if [ $NUM_ERRORS -eq 0 ]
then
    echo "No Errors!"
    rm -f $ERRORFILES
else
    echo "********** ERRORS ************* $NUM_ERRORS files had errors:"
    cat $ERRORFILES
    if [ $# -gt 0 ]
    then
        sed 's,^,doc/,' $ERRORFILES >> "$1"
    fi
    rm -f $ERRORFILES
    exit $NUM_ERRORS
fi
